nspcc-dev/dbft

- dbft.go
- dbft_test.go
In case when all transaction were already in pool by the time `PrepareRequest` was received, perform verification immediately.
Also add tests.
> Fix a bug with missed verification

- go.mod
- go.sum
I want to update rfc6979 package in neo-go and it can't be done without a similar update here.
> go.mod: update to neofs-crypto v0.2.3

- config.go
- context.go
- send.go
Sometimes a node can have more than one key pair.
In this case even if the set of validators has been changed,
node can still have another public key which can be used.
It will make it easier to implement behavior similar to C# node.
https://github.com/neo-project/neo/blob/master/src/neo/Consensus/ConsensusContext.cs#L380
> Invoke GetKeyPair after every block

- dbft.go
It can lead to the node being late to trigger a ChangeView when it's the
chosen one to process RecoveryRequest. Fixes #16.
> dbft: don't extend timer when commit is from a different view

- check.go
- dbft.go
- send.go
It's not exactly the same after this change, but it's a little closer and
allows to track consensus node state without debug enabled.
> log more at info level, follow (some of) neo-cli behavior

- context.go
- dbft.go
- timer/timer.go
- timer/timer_test.go
It should Extend() by additive amount of time.
All multiplication is performed in extendTimer in dbft.go .
https://github.com/neo-project/neo/blob/master/src/neo/Consensus/ConsensusService.cs#L248
> Fix timer.Extend()

- dbft.go
* no messages were printed for good PrepareRequests and PrepareResponses
received
* downplay 'missing tx' message also from warning to info because it's
normal to the node operation
* don't spew out 'missing tx' hashes as there could be many of them
> dbft: tune logging a bit more

- context.go
- dbft.go
These patches are intended to improve behavior of an outdated (after reset) node that should be able to catch up with other ones eventually, but fails to do so at the moment.
> Improve stale node behavior

- send.go
These events are significant in normal node operation and it's important which
one we'll actually see here.
> send: raise changeView log messages priority

- check.go
- dbft.go
Closes #34 .
Remove `blockPersistTime` field and calculate timeout value
based on current view only. Time passed between block persist and
calling `InitializeConsensus` is of the order of milliseconds and is
assumed to be negligible.
This is needed because blocks can be acquired via network.
In this case persisting is done outside of dbft library.
> dbft: fix timeout calculation in `InitializeConsensus`

- config.go
- context.go
- dbft_test.go
- simulation/main.go
After adding native Policy contract, GetVerifyed has it's own policy, so
we don't use TxPerBlock anywhere.
> *: remove TxPerBlock method

- payload/constructors.go
- payload/message.go
- payload/message_test.go
- payload/recovery_message.go
They were intended to be used for signing and verification which is now not a part of this library.
> Remove marshaling methods from the ConsensusPayload interface

- simulation/main.go
- timer/timer.go
- timer/timer_test.go
There is no need for it, dbft is single-threaded. All users need to be updated
like this and that's it:
-               case hv := <-s.dbft.Timer.C():
+               case <-s.dbft.Timer.C():
+                       hv := s.dbft.Timer.HV()
> timer: remove goroutine from the timer

- check.go
- context.go
- dbft.go
Make block timing more accurate under load. BlockIndex is needed to
distinguish between consensus-produced block and the one added via regular
block addition mechanism.
See neo-project/neo#1959 and neo-project/neo#1960.
> dbft: adjust timer setting by the block processing time

- config.go
- context.go
Timer provides time in nano-seconds. If clients use milliseconds
timestamps, `Timestamp` increment will not be reflected.
> dbft: increment Timestamp by millisecond

- .github/workflows/go.yml
- context.go
If timestamp is cut (from ns to ms), local context can have timestamp
which differs from other context. This can lead to a situation when
|request timestamp - context timestamp| is less than
`TimestampIncrement`, but which is valid from the POV of other nodes.
> dbft: use `TimestampIncrement` as granularity

- dbft.go
- dbft_test.go
When transaction added is the only missing tx and we have all messages
to go to the next height this will be done and `MissingTransactions`
field will be cleared.
> dbft: fix possible panic in `OnTransaction()`

- config.go
- dbft_test.go
- payload/message.go
- payload/recovery_message.go
- send.go
Implement things needed for new extensible payloads for consensus in neo-go.
> Move `Version` and `PrevHash` to `PrepareRequest`

- context.go
Consider the situation when ChangeView was received and Context's block
was reset. If we receive PrepareResponse or Commit on this stage, then
the old block will be recreated, because we haven't got new PrepareRequest
with the newly proposed block. All newly-received Commits will fail
verification then.
> context: do not create header until PrepareRequest is received/sent

- dbft.go
If F nodes are down, consensus should be able to function, so at least
F+1 nodes must be able to respond.
Refs. https://github.com/neo-project/neo-modules/issues/722
Signed-off-by: Evgenii Stratonikov <evgeniy@nspcc.ru>
> dbft: increase amount of nodes responding to RecoveryRequest

- context.go
They're used to create recovery messages and currently we're completely
missing CV payloads there because of this logic. In fact we want to save
messages that lead to the current view we're resetting the state for (==), but
newer ones don't hurt also (>=), even though we shouldn't have them. See C#
implementation.
> context: correctly save previous change view payloads during view reset

- check.go
- context.go
- dbft.go
- dbft_test.go
- simulation/main.go
And always check new timestamp against it, timestamps can only move forward with each block.
> dbft: use previous block timestamp for view 0 initialization

- formal-models/dbft/dbft.tla
Primary node can't send the CV from "initialized" stage, see the https://github.com/nspcc-dev/dbft/blob/64d1eec86ace1995086b1ec5ae18da2b1bbbb4ac/dbft.go#L190.
> models: adjust enabling condition for CV sending

- context.go
- dbft_test.go
OK, @roman-khimov, let's move on with it. Look carefully at the test, please, there's a suggestion about recovery messages accounting.
Port of https://github.com/roman-khimov/dbft/pull/3 with the test added.
> dbft: fix the deadlock reason in four-good-nodes setup

- payload/consensus_message.go
- payload/recovery_message.go
Should be a part of https://github.com/nspcc-dev/dbft/pull/72, but turns out that Goland's "Find and replace" manager searches over vendor directory as far and does not include the whole set of search results if there are too many of them.
> *: replace `interface{}` with `any` keyword

- dbft.go
We have timer, and we should follow it. Close #74.
> dbft: do not send PrepareRequest immediately after Recovery message

- .github/workflows/dco.yml
Have a single source of true DCO check.
> workflows: use dco from org-wide .github

- dbft.go
PrepareRequest and PrepareResponse are ignored not only because of view changing. Wrong log is misleading, so we'd better have the log that reflects the real state of things.
> dbft: improve "ignoring"-related debug messages

- .github/workflows/build.yml
- .github/workflows/go.yml
- CHANGELOG.md
- docs/release-instruction.md
In this PR:
* add CHANGELOG
* add release instructions
* take care of GitHub workflows
> *: release related improvements

- crypto/ecdsa.go
- go.mod
- go.sum
It's just a test code in its essence, so it doesn't matter what it uses.
> crypto: drop neofs-crypto dependency

- .github/workflows/build.yml
- .github/workflows/go.yml
For linter job only. Port
https://github.com/nspcc-dev/neofs-contract/pull/389/commits/e0ec4d24cb992232935a17b59c09927cbc842444.
> .github: use minimum required Go version from go.mod file

- change_view.go
- commit.go
- config.go
- consensus_message.go
- consensus_payload.go
- dbft_test.go
- internal/payload/change_view.go
- internal/payload/commit.go
- internal/payload/consensus_message.go
- internal/payload/constructors.go
- internal/payload/message.go
- internal/payload/message_test.go
- internal/payload/prepare_request.go
- internal/payload/prepare_response.go
- internal/payload/recovery_message.go
- internal/payload/recovery_request.go
- internal/simulation/main.go
- prepare_request.go
- prepare_response.go
- recovery_message.go
- recovery_request.go
- send.go
Ref. https://github.com/nspcc-dev/dbft/issues/84#issuecomment-1976441193.
> dbft: remove useless setters of dBFT interfaces

- CHANGELOG.md
- README.md
- config.go
- context.go
- dbft.go
- dbft_test.go
- internal/consensus/consensus.go
- internal/simulation/main.go
- timer.go
- timer/timer.go
- timer/timer_test.go
Take a look, suggestions are welcome. But I think it's easier to use this way.
> timer: drop HV interface, use it less often

- config.go
- dbft.go
- dbft_test.go
- internal/consensus/consensus.go
- internal/simulation/main.go
Feedback from the integration with NeoGo.
> Final user-facing interface improvements

- .github/workflows/go.yml
Warning: CodeQL Action v2 will be deprecated on December 5th, 2024. Please update all occurrences of the CodeQL Action in your workflow files to v3. For more information, see https://github.blog/changelog/2024-01-12-code-scanning-deprecation-of-codeql-action-v2/
> workflows: update CodeQL version

- CHANGELOG.md
- config.go
- dbft_test.go
- identity.go
- internal/consensus/block.go
- internal/consensus/consensus.go
- internal/crypto/crypto_test.go
- internal/crypto/ecdsa.go
- internal/crypto/ecdsa_test.go
- internal/simulation/main.go
Just something I have on hands left after Neo X dependencies upgrade.
> Simplify library interfaces a bit

- .golangci.yml
> Take care of linter configuration

- block.go
- check.go
- commit.go
- config.go
- consensus_message.go
- consensus_message_type.go
- context.go
- dbft.go
- dbft_test.go
- helpers.go
- helpers_test.go
- internal/consensus/amev_block.go
- internal/consensus/amev_commit.go
- internal/consensus/amev_preBlock.go
- internal/consensus/amev_preCommit.go
- internal/consensus/compact.go
- internal/consensus/consensus_message.go
- internal/consensus/constructors.go
- internal/consensus/recovery_message.go
- internal/consensus/transaction.go
- internal/simulation/main.go
- pre_block.go
- pre_commit.go
- recovery_message.go
- send.go
WIP, just something I have on hands right now, need to test it and integrate with NeoGo/NeoX nodes.
TODO:
Ref. #112.
> *: support extra dBFT stage

- dbft.go
- dbft_test.go
It's obviously better this way.
> dbft: replace boring cycle with fancy condition

- CHANGELOG.md
- context.go
I just don't believe it's possible, I was sure that I've added this resetting code. Required for https://github.com/bane-labs/go-ethereum/pull/287.
> context: properly reset preBlock and preHeader

- CHANGELOG.md
- send.go
PreHeader is not enough to create PreCommit because PreCommit requires the whole set of transactions to be available for PreCommit data calculations. This bug leads to the fact that Primary node can't properly construct valid PreCommit message because block's transactions are not yet filled by dBFT by this moment.
Required by https://github.com/bane-labs/go-ethereum/pull/287.
Draft because I need to carefully ensure that nothing is broken by this change for non-primary nodes. I checked that `CreatePreBlock` is called only when all transactions are available (as expected).
> send: construct PreBlock instead of PreHeader to create PreCommit

- CHANGELOG.md
- check.go
- config.go
- context.go
- dbft.go
- dbft_test.go
- pre_block.go
The necessity of this extension is described in https://github.com/bane-labs/go-ethereum/pull/301#discussion_r1726514210. We need at least `M` _correct_ PreCommits to decrypt Envelopes content, but decryption may be checked only by using the group of PreCommits. Thus, we can't say whether a single PreCommit can/can't decrypt Envelopes content.
@roman-khimov, please, review it carefully, I checked what I could and there seems to be no tricks possible to skip verification, but maybe you'll fined something. May be it'll be easier to review if you take a look at https://github.com/bane-labs/go-ethereum/pull/287/commits/f4e830c751ae6a4ee94adb6db42096133abfa235.
> *: extend PreBlock processing callback

- CHANGELOG.md
- context.go
Processing block should be taken into account while checking anti-MEV extension enabling height.
> context: enable anti-MEV extension starting from specified height

- CHANGELOG.md
- context.go
- dbft.go
NeoX node is struggling from inability to receive PreBlock instead of PreHeader.
> contest: expose PreBlock instead of PreHeader

- CHANGELOG.md
- dbft.go
Fix a bug introduced by ffa8c1fc3299a2f710225a0aa14407c26641694f.
> dbft: prohibit WatchOnly to send RecoveryMessage

- CHANGELOG.md
- identity.go
- internal/consensus/amev_block.go
- internal/consensus/block.go
- internal/consensus/block_test.go
- internal/crypto/crypto_test.go
PrivateKey.Sign() is not used by dBFT in any way. Block signing process is managed by Block.Sign() and PreBlock.SetData() methods, whereas consensus payload signing is out of dbft scope.
> identity: simplify PrivateKey interface

- CHANGELOG.md
- check.go
Problem:
Inappropriate message in the WatchOnly node logs with NeoXAMEV extension enabled:
```
2024-12-05T15:15:54.366+0300	INFO	dbft@v0.3.1/dbft.go:545	received PreCommit	{"validator": 5}
2024-12-05T15:15:54.366+0300	DEBUG	dbft@v0.3.1/check.go:90	can't send commit since self preCommit not yet sent
```
Based on these logs it may seem that WatchOnly is trying (or will try) to send Commit. It must never happen, hence I dived into the library code and discovered the condition that was added mostly for safety and that was planned to be removed in future:
https://github.com/nspcc-dev/dbft/blob/7c005d93e4b47106b679e3cc55d182f8167e0e56/check.go#L82-L84
Ref. https://github.com/nspcc-dev/dbft/pull/118#discussion_r1681631842.
So the problem is in the invalid documentaiton and in improper log …
> check: prohibit WatchOnly to send commits

- CHANGELOG.md
- context.go
- dbft.go
- rtt.go
- send.go
After b3c1c3b1a14f2070fed481d077a6daada6382b3e the only source of block time inaccuracy left is PrepareRequest propagation. In general it's undetermined and can vary from node to node and from round to round. But in practice it's relatively stable and can be averaged out over some number of samples. While backup node can't know when request was sent to it, it can measure what happens to its request when it's primary since healthy nodes are expected to respond immediately making request/response pretty similar to ping/pong roundtrip. This data also can't be perfect, messages can travel different ways from A to B and B to A on a P2P network, but in practice it's good enough and it's much better than having no data at all.
Notice that this timer adjustment scheme uses local timer only, we …
> context: add simple rtt estimator

- go.mod
- go.sum
- internal/crypto/ecdsa.go
- internal/crypto/ecdsa_test.go
- internal/simulation/main.go
We don't need murmur3 to sort validators and we don't need serialization code since a129fd72f1773c7f7f05b7b5bfa60703a645e676.
> crypto/simulation: drop dead code and dependency

- CHANGELOG.md
- context.go
- send.go
It's an open question what should we do when the node failed to sign the block.
> Log error on commit construction

- .github/workflows/changelog_update.yml
It was recently compromised and even though changes to tags were reverted it's still worth upgrading (GH also warns about <=45.0.7).
See https://github.com/tj-actions/changed-files/issues/2463
> workflows: update tj-actions/changed-files to v46

- CHANGELOG.md
- check.go
- config.go
- context.go
- dbft.go
- dbft_test.go
- internal/consensus/consensus.go
- send.go
Ref. https://github.com/nspcc-dev/neo-go/issues/3745.
Let's firstly finalize https://github.com/nspcc-dev/neo-go/pull/3835 before the merge, because we might want to add `height` parameter to `WithSecondsPerBlock` setting (to me it's not needed, but still may be considered).
> *: adapt state-dependent block producing time

- timer/timer.go
This reverts commit 8dfda6b83b60dc59ccd6cbdf134831d495a5abf9 and f7a23ed.
This change is needed because external users of the library should be able to stop the dBFT timer:
https://github.com/nspcc-dev/neo-go/blob/3e54c46281237124da7fd89a90501a9d58a3aa60/pkg/consensus/consensus.go#L342
> Revert timer related changes

- CHANGELOG.md
- config.go
- context.go
- dbft.go
- dbft_test.go
- send.go
The most part of transaction awaiting logic is managed by NeoGo, so dBFT is not changed a lot.
TODO:
Close #149.
An example of block with a single transaction accepted prior to MaxtimePerBlock (consensus with 1s-20 block time):
```
2025-07-11T15:38:34.748Z	INFO	dbft@v0.3.3-0.20250711145350-dacd9067b3f7/check.go:130	approving block	{"height": 2, "hash": "f0d777dbf57bb9d98c68f7eb9707ee032cbd325aa92209579452970e7a42e918", "tx_count": 0, "merkle": "0000000000000000000000000000000000000000000000000000000000000000", "prev": "79ef87a82d2850bf938a34a2e36ef7116822bd2d93717a4dd98cf2049087086f"}
2025-07-11T15:38:34.748Z	DEBUG	consensus/consensus.go:379	received message	{"from": 0, "type": "Commit"}
2025-07-11T15:38:34.748Z	DEBUG	dbft@v0.3.3-0.20250711145350-dacd9067b3f7/dbft.go:259	received message …
```
> *: support dynamic block time

- CHANGELOG.md
- README.md
- dbft.go
NeoGo node works OK with this version. NeoX requires Go version upgrade from 1.22 to 1.23, but consensus on privnet also works afterwards.
> CHANGELOG: release v0.4.0
